version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fleet_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    volumes:
      - fleetops_postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - fleet_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: fleet_gateway
    ports:
      - "${GATEWAY_PORT_EXTERNAL}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - ROUTING_SERVICE_URL=http://routing-service:8081/route
      - APP_JWT_SECRET=${JWT_SECRET}
      - APP_JWT_EXPIRATION=${JWT_EXPIRATION_MS}
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - fleet_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fleet_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fleet_net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  routing-service:
    build:
      context: ./routing-service
      dockerfile: Dockerfile
    container_name: fleet_routing
    expose:
      - "8081"
    networks:
      - fleet_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: fleet_prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fleet_net

  loki:
    image: grafana/loki:2.9.0
    container_name: fleet_loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
     - "3100:3100"
    networks:
     - fleet_net

  grafana:
    image: grafana/grafana:latest
    container_name: fleet_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - fleet_net

networks:
   fleet_net:
     driver: bridge

volumes:
  fleetops_postgres_data: